// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping.Domain;

#nullable disable

namespace Shipping.Migrations
{
    [DbContext(typeof(ShippingContext))]
    [Migration("20251206212259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shipping.Domain.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssignedItineraryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeliveryHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DeliverySpecificationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedItineraryId");

                    b.HasIndex("DeliveryHistoryId");

                    b.HasIndex("DeliverySpecificationId");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("Shipping.Domain.CarrierMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScheduleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ToId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("CarrierMovements", (string)null);
                });

            modelBuilder.Entity("Shipping.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Shipping.Domain.DeliveryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DeliveryHistory");
                });

            modelBuilder.Entity("Shipping.Domain.DeliverySpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LatestArrival")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("DeliverySpecification");
                });

            modelBuilder.Entity("Shipping.Domain.HandlingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarrierMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarrierMovementId");

                    b.HasIndex("LocationId");

                    b.ToTable("HandlingEvents", (string)null);
                });

            modelBuilder.Entity("Shipping.Domain.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Itinerary");
                });

            modelBuilder.Entity("Shipping.Domain.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LoadLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LoadTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UnloadLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UnloadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VesselVoyageId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("LoadLocationId");

                    b.HasIndex("UnloadLocationId");

                    b.ToTable("Leg");
                });

            modelBuilder.Entity("Shipping.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Shipping.Domain.Cargo", b =>
                {
                    b.HasOne("Shipping.Domain.Itinerary", "AssignedItinerary")
                        .WithMany()
                        .HasForeignKey("AssignedItineraryId");

                    b.HasOne("Shipping.Domain.DeliveryHistory", "DeliveryHistory")
                        .WithMany()
                        .HasForeignKey("DeliveryHistoryId");

                    b.HasOne("Shipping.Domain.DeliverySpecification", "DeliverySpecification")
                        .WithMany()
                        .HasForeignKey("DeliverySpecificationId");

                    b.Navigation("AssignedItinerary");

                    b.Navigation("DeliveryHistory");

                    b.Navigation("DeliverySpecification");
                });

            modelBuilder.Entity("Shipping.Domain.CarrierMovement", b =>
                {
                    b.HasOne("Shipping.Domain.Location", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("Shipping.Domain.Location", "To")
                        .WithMany()
                        .HasForeignKey("ToId");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Shipping.Domain.DeliverySpecification", b =>
                {
                    b.HasOne("Shipping.Domain.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Shipping.Domain.HandlingEvent", b =>
                {
                    b.HasOne("Shipping.Domain.CarrierMovement", "CarrierMovement")
                        .WithMany()
                        .HasForeignKey("CarrierMovementId");

                    b.HasOne("Shipping.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("CarrierMovement");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Shipping.Domain.Leg", b =>
                {
                    b.HasOne("Shipping.Domain.Itinerary", null)
                        .WithMany("Legs")
                        .HasForeignKey("ItineraryId");

                    b.HasOne("Shipping.Domain.Location", "LoadLocation")
                        .WithMany()
                        .HasForeignKey("LoadLocationId");

                    b.HasOne("Shipping.Domain.Location", "UnloadLocation")
                        .WithMany()
                        .HasForeignKey("UnloadLocationId");

                    b.Navigation("LoadLocation");

                    b.Navigation("UnloadLocation");
                });

            modelBuilder.Entity("Shipping.Domain.Itinerary", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
